import Link from "next/link";
import { ArrowIcon } from "@/components/icons/CustomIcons";
import { articlesEn, processEn, projectsEn, servicesEn } from "@/data/content-en";
import { technologyCategories } from "@/data/technologies";

export function EnglishSections() {
  return (
    <>
      <section id="services" className="scroll-mt-24 border-y border-slate-200 bg-white px-6 py-24"><div className="mx-auto max-w-7xl"><Heading label="Services" title="Solutions for more reliable and efficient environments" text="Hands-on technical work focused on infrastructure, reliability, automation and cloud operations." /><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{servicesEn.map((service, index) => <article key={service.slug} className="light-card rounded-3xl border border-slate-200 bg-white p-7"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-blue-50 text-sm font-bold text-blue-600">0{index + 1}</span><h3 className="mt-7 text-lg font-bold uppercase leading-7 text-slate-900">{service.title}</h3><p className="mt-4 leading-7 text-slate-600">{service.description}</p></article>)}</div></div></section>

      <section id="process" className="scroll-mt-24 bg-[#EEF4FF] px-6 py-24"><div className="mx-auto max-w-7xl"><Heading label="How it works" title="A clear process from assessment to delivery" text="Every engagement starts with context and progresses through clear priorities, technical follow-up and aligned deliverables." /><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{processEn.map(([step, title, text]) => <article key={step} className="light-card rounded-3xl border border-white bg-white/80 p-7"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-gradient-to-br from-blue-600 to-violet-600 text-sm font-bold text-white">{step}</div><h3 className="mt-6 text-xl font-bold text-slate-900">{title}</h3><p className="mt-4 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>

      <section id="about" className="scroll-mt-24 border-y border-slate-200 bg-white px-6 py-24"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[1.05fr_0.95fr]"><div><p className="section-label">About</p><h2 className="section-title">DevOps and SRE applied to production environments</h2><div className="mt-8 space-y-5 text-lg leading-8 text-slate-600"><p>I am a DevOps Engineer and SRE with more than three years of experience in cloud infrastructure, automation, Kubernetes, CI/CD and observability.</p><p>I work with AWS, Terraform, Docker, Kubernetes, Helm, GitHub Actions, Jenkins and Argo CD, as well as Prometheus, Grafana, Loki, Elastic Stack and OpenTelemetry.</p><p>Through FSO Cloud Consulting, I apply this experience to build reliable, automated solutions aligned with each environment&apos;s needs.</p></div></div><div className="grid gap-4">{["3+ years in DevOps and SRE", "Hands-on production experience", "AWS, Terraform, Kubernetes, CI/CD and GitOps", "Observability, troubleshooting and reliability"].map((item, index) => <div key={item} className="light-card flex items-center gap-5 rounded-3xl border border-slate-200 bg-[#F8FAFD] p-6"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-white font-bold text-blue-600">0{index + 1}</span><p className="font-semibold text-slate-700">{item}</p></div>)}</div></div></section>

      <section id="projects" className="scroll-mt-24 bg-[#F3F6FB] px-6 py-24"><div className="mx-auto max-w-7xl"><Heading label="Projects and technical cases" title="Experience applied to real challenges" text="Technical cases that demonstrate a practical approach to reliability, automation and infrastructure." /><article className="light-card mt-14 rounded-[32px] border border-slate-200 bg-white p-7 md:p-10"><div className="flex justify-between gap-4"><span className="rounded-full bg-blue-50 px-4 py-2 text-xs font-bold text-blue-700">{projectsEn.featured.category}</span><span className="rounded-full bg-emerald-100 px-4 py-2 text-xs font-bold text-emerald-700">COMPLETED</span></div><h3 className="mt-7 text-3xl font-bold text-slate-950 md:text-4xl">{projectsEn.featured.title}</h3><p className="mt-5 max-w-3xl text-lg leading-8 text-slate-600">{projectsEn.featured.description}</p><div className="mt-9 grid gap-5 lg:grid-cols-3"><CaseItem label="Challenge" text={projectsEn.featured.challenge} /><CaseItem label="Solution" text={projectsEn.featured.solution} blue /><CaseItem label="Outcome" text={projectsEn.featured.result} green /></div><Link href={`/en/projects/${projectsEn.featured.slug}/`} className="mt-8 inline-flex items-center gap-3 rounded-xl bg-blue-600 px-6 py-4 text-sm font-bold text-white">View full case <ArrowIcon /></Link></article><div className="mt-8 grid gap-6 md:grid-cols-2">{projectsEn.upcoming.map(([category, title, text]) => <article key={title} className="light-card rounded-3xl border border-slate-200 bg-white p-7"><span className="text-xs font-bold text-blue-600">{category}</span><h3 className="mt-6 text-xl font-bold text-slate-900">{title}</h3><p className="mt-4 leading-7 text-slate-600">{text}</p><span className="mt-6 inline-flex rounded-full bg-slate-100 px-3 py-1.5 text-xs font-bold text-slate-500">COMING SOON</span></article>)}</div></div></section>

      <section id="articles" className="scroll-mt-24 border-y border-slate-200 bg-white px-6 py-24"><div className="mx-auto max-w-7xl"><Heading label="Articles and knowledge" title="Technical content for better decisions" text="Practical perspectives on DevOps, SRE, Cloud and Observability." /><div className="mt-14 grid gap-6 lg:grid-cols-3">{articlesEn.map(([category, title, text]) => <article key={title} className="light-card rounded-3xl border border-slate-200 bg-white p-7"><span className="text-xs font-bold text-blue-600">{category}</span><h3 className="mt-8 text-2xl font-bold text-slate-900">{title}</h3><p className="mt-5 leading-7 text-slate-600">{text}</p><span className="mt-7 inline-flex text-sm font-bold text-blue-600">Coming soon</span></article>)}</div></div></section>

      <section id="technologies" className="scroll-mt-24 bg-[#EDF4FF] px-6 py-24"><div className="mx-auto max-w-7xl"><Heading label="Technologies and capabilities" title="Tools selected for the challenge" text="Technology is chosen according to context, goals, architecture and operational maturity." /><div className="mt-14 grid gap-6 md:grid-cols-2 lg:grid-cols-4">{technologyCategories.map((category) => <article key={category.title} className={`light-card rounded-3xl border border-white bg-white/80 p-7 ${category.featured ? "lg:col-span-2" : ""}`}><h3 className="text-sm font-bold uppercase text-slate-950">{category.title}</h3><div className="mt-6 flex flex-wrap gap-2">{category.technologies.map((technology) => <span key={technology.name} className="rounded-full bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700">{technology.name}</span>)}</div></article>)}</div></div></section>
    </>
  );
}

function Heading({ label, title, text }: { label: string; title: string; text: string }) { return <div className="max-w-3xl"><p className="section-label">{label}</p><h2 className="section-title">{title}</h2><p className="section-description">{text}</p></div>; }
function CaseItem({ label, text, blue, green }: { label: string; text: string; blue?: boolean; green?: boolean }) { return <div className={`rounded-2xl border p-6 ${green ? "border-emerald-200 bg-emerald-50" : blue ? "border-blue-100 bg-blue-50" : "border-slate-200 bg-slate-50"}`}><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-4 leading-7 text-slate-700">{text}</p></div>; }
