import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Sections";
import { ArrowIcon } from "@/components/icons/CustomIcons";
import { servicesEn } from "@/data/content-en";
import { siteConfig } from "@/lib/site";

type Props = { params: Promise<{ slug: string }> };
export const dynamicParams = false;
export function generateStaticParams() { return servicesEn.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const service = servicesEn.find(item => item.slug === slug); return service ? { title: `${service.title} | FSO Cloud Consulting`, description: service.description, alternates: { canonical: `${siteConfig.url}/en/services/${slug}/` } } : {}; }

export default async function EnglishServicePage({ params }: Props) {
  const { slug } = await params; const service = servicesEn.find(item => item.slug === slug); if (!service) notFound();
  const deliverables = ["Architecture and operations assessment", "Prioritized recommendations and a practical implementation plan", "Configuration, validation, and technical documentation", "Knowledge transfer and operational guidance"];
  const benefits = ["Clear technical priorities and lower operational risk", "More consistent, observable, and maintainable environments", "Engineering decisions aligned with reliability and business needs"];
  return <><Header locale="en" /><main className="bg-[#F8FAFD] pt-24 text-slate-900"><section className="border-b border-slate-200 px-6 py-20 md:py-28"><div className="mx-auto max-w-5xl"><Link href="/en/#services" className="text-sm font-semibold text-blue-600">← Back to services</Link><p className="section-label mt-10">Specialized service</p><h1 className="mt-5 max-w-4xl text-4xl font-bold tracking-[-0.04em] md:text-6xl">{service.title}</h1><p className="mt-7 max-w-3xl text-xl leading-9 text-slate-600">{service.description}</p></div></section><section className="bg-white px-6 py-20"><div className="mx-auto grid max-w-5xl gap-12 lg:grid-cols-2"><div><p className="section-label">Overview</p><h2 className="section-title">How I can help</h2><p className="mt-7 text-lg leading-8 text-slate-600">I tailor each engagement to the environment, the team's operational maturity, and the business priorities. The work combines assessment, implementation, validation, and clear documentation.</p></div><aside className="rounded-3xl border border-blue-100 bg-blue-50 p-8"><p className="text-xs font-bold uppercase tracking-wider text-blue-600">Best suited for</p><p className="mt-4 leading-7 text-slate-700">Teams looking to reduce operational risk, improve reliability, and establish practices they can sustain over time.</p></aside></div></section><section className="border-y border-slate-200 bg-[#F3F6FB] px-6 py-20"><div className="mx-auto grid max-w-5xl gap-12 lg:grid-cols-2"><div><p className="section-label">Deliverables</p><h2 className="section-title">What the engagement can include</h2><ul className="mt-8 grid gap-4">{deliverables.map(item => <li key={item} className="rounded-2xl border border-slate-200 bg-white p-5 text-slate-700">{item}</li>)}</ul></div><div><p className="section-label">Outcomes</p><h2 className="section-title">What your team gains</h2><ul className="mt-8 grid gap-4">{benefits.map(item => <li key={item} className="rounded-2xl bg-white p-5 text-slate-700 shadow-sm">{item}</li>)}</ul></div></div></section><section className="bg-white px-6 py-20"><div className="mx-auto max-w-5xl rounded-[36px] bg-[#101C3C] p-8 text-white md:p-14"><p className="text-sm font-bold uppercase tracking-wider text-blue-300">Next step</p><h2 className="mt-5 max-w-3xl text-3xl font-bold md:text-5xl">Let's find the right approach for your environment.</h2><Link href="/en/#contact" className="mt-8 inline-flex items-center gap-3 rounded-xl bg-white px-6 py-4 text-sm font-bold text-blue-700">Discuss this service <ArrowIcon /></Link></div></section></main><Footer locale="en" /></>;
}
